#:schema node_modules/wrangler/config-schema.json
name = "delicate-dust-8d19"
compatibility_date = "2024-09-09"
main = "./build/worker/index.js"
experimental_assets = { directory = "./build/client" }
